### ISSUE TITLE
test install and running on different computers

### ISSUE THREAD

**Issue by DanOvando** [DanOvando/marlin#12]
@echelleburns try installing and running the package on your end. If it works close this issue, thanks!

**Comment by echelleburns** [comment]
Using RStudio version: 1.2.5042; R version: R 3.6.3 GUI 1.70 El Capitan build (7735)
Running on macOS Catalina version 10.15.5

**Difficulty with Installing Package**

Originally tried installing using suggested `devtools::install_github("DanOvando/marlin")` but was getting the following error: 

> clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘marlin’
 removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/marlin’
Error: Failed to install 'marlin' from GitHub:
  (converted from warning) installation of package ‘/var/folders/rx/7crxyq5966bfcxggfm76vpdr0000gn/T//RtmpJscjhu/file15797444d47f/marlin_0.0.0.9000.tar.gz’ had non-zero exit status

Followed the instructions [here](https://www.r-bloggers.com/using-osx-compiling-an-r-package-from-source-issues-with-fopenmp-try-this/) and re-ran `devtools::install_github("DanOvando/marlin")`. Then getting the following error: 

> Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 72.194.34.74. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.
  Rate limit remaining: 0/60
  Rate limit reset at: 2020-07-08 22:37:02 UTC
  To increase your GitHub API rate limit
   Use `usethis::browse_github_pat()` to create a Personal Access Token.
   Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.

Created a personal access token for GITHUB_PAT in the .Renviron and was met with the first error again.

**Comment by DanOvando** [comment]
Ah fun! This has to do with compiling c++ code on Macs pre R 4.0, and an option that RcppEigen uses. 

Easiest option, might be time to migrate to R v4.0, but remember that that will require reinstall of all your packages, so maybe not the best thing to do if you're on a deadline. 

Actually purely for testing, might be best to make sure you can get it to work on 3.6

If you can, follow the instructions [here](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos-before-r-4.0.0/) to set up R compile c++ code properly on a Mac. 

once you've confirmed that by running the "quick check" in that link, try installing `marlin` again.

**Comment by echelleburns** [comment]
Success! 

Was able to download this time and run your example code in your readme (did require setting up an access token and account with NCBI)

**Comment by DanOvando** [comment]
Cool, did it require an account with NCBI or just ask for it?

**Comment by echelleburns** [comment]
It required the creation of an NCBI account to get an API access token to add to .Renviron

Message to create NCBI account and create API access token.
> No ENTREZ API key provided
 Get one via taxize::use_entrez()
See https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
> taxize::use_entrez()

Message to add access key to the .Renviron

> Create your key from your (brand-new) account's. 
 After generating your key set it as ENTREZ_KEY in .Renviron.
 ENTREZ_KEY='youractualkeynotthisstring'
 For that, use usethis::edit_r_environ()

Once I added the ENTREZ_KEY and restarted R, it worked fine.

**Comment by DanOvando** [comment]
Interesting, thanks for letting me know. Need that to lookup the scientific name if someone supplies a common name. I'll add that to the documentation
