### ISSUE TITLE
vignette issue: process_marlin() output's step parameter cannot be filtered without first specifying fauna list

### ISSUE THREAD

**Issue by echelleburns** [DanOvando/marlin#43]
Running through the vignette marlin.Rmd (no code changes), and it was throwing an an error from line 158: Error in UseMethod("filter_") : no applicable method for 'filter_' applied to an object of class "list". 

``` r
proc_nearshore <- process_marlin(nearshore, time_step =  fauna[[1]]$time_step)

proc_nearshore %>%
  filter(step == max(step)) %>%
  group_by(x, y, critter) %>%
  summarise(ssb = sum(ssb)) %>%
  group_by(critter) %>%
  mutate(ssb = ssb / max(ssb)) %>%
  ggplot(aes(x, y, fill = ssb)) +
  geom_tile() +
  scale_fill_viridis_c(
    name = "Density",
    guide = guide_colorbar(
      frame.colour = "black",
      tick.colour = "black",
      nbin = 1000,
      barwidth = unit(15, "lines")
    )
  ) +
  facet_wrap( ~ critter) +
  theme(legend.position = "top")
```
<sup>Created on 2020-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Likely to do with recent changes in `process_marlin()` function return. 

https://github.com/DanOvando/marlin/blob/f7c8052d2fe3051617265b63f09ec98604cfa8ca/R/process-marlin.R#L120-L121

Code runs if you make the following amendment:

``` r
proc_nearshore$fauna %>%
  filter(step == max(step)) %>%
  group_by(x, y, critter) %>%
  summarise(ssb = sum(ssb)) %>%
  group_by(critter) %>%
  mutate(ssb = ssb / max(ssb)) %>%
  ggplot(aes(x, y, fill = ssb)) +
  geom_tile() +
  scale_fill_viridis_c(
    name = "Density",
    guide = guide_colorbar(
      frame.colour = "black",
      tick.colour = "black",
      nbin = 1000,
      barwidth = unit(15, "lines")
    )
  ) +
  facet_wrap( ~ critter) +
  theme(legend.position = "top")
```
<sup>Created on 2020-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DanOvando** [comment]
Ah crap, I forgot that I've been working on the development branch, not the master https://github.com/DanOvando/marlin/tree/dev, I think the main branch is broken in a few ways, but the dev branch should work fine at the moment, unless this was on the dev branch?

**Comment by echelleburns** [comment]
Ah gotcha - it was on the master branch, but it looks like the problem persists in the dev branch as well.

**Comment by DanOvando** [comment]
Ah gotcha, oh man I'm being the worst here. I moved everything into the README, since before it was confusingly scattered between the README and the vignette. So use the README to work through examples, and we can go ahead and delete the vignette until we come up with a use for one
