### ISSUE TITLE
Website update (typo): Evaluating MPAs

### ISSUE THREAD

**Issue by echelleburns** [DanOvando/marlin#78]
In the [Evaluating MPAs](https://danovando.github.io/marlin/#evaluating-mpas) section, when the MPA network is being created, it is plotted using the following code: 

```
mpa_locations %>% 
  ggplot(aes(x,y, fill = mpa)) + 
  geom_tile() + 
  scale_fill_brewer(palette = "Accent", direction  = -1, name = "MPA") + 
  scale_x_continuous(name = "Lat") + 
  scale_y_continuous(name = "Lon")
```

Are the names for the x and y axes correct, or should they be switched?

**Comment by DanOvando** [comment]
Good catch! fixing
