### ISSUE TITLE
Optimize MPA vignette - Questionable result?

### ISSUE THREAD

**Issue by echelleburns** [DanOvando/marlin#82]
There is a result in the Open Access and MPAs section that I feel does not make sense with the commentary in this vignette. In chunk 4: 

```
set.seed(42)
#specify some MPA locations
mpa_locations <- expand_grid(x = 1:resolution, y = 1:resolution) %>%
mutate(mpa = x > 4 & y < 6)

with_mpa <- simmar(fauna = fauna,
                  fleets = fleets,
                  years = years,
                  manager = list(mpas = list(locations = mpa_locations,
              mpa_year = floor(years * .5))))

proc_mpa_sim <- process_marlin(with_mpa)


proc_mpa_sim$fleets %>% 
  pivot_longer(contains("_effort"), names_to = "fleet2", values_to = "effort") %>% 
  group_by(step, fleet2) %>%
  summarise(effort = sum(effort)) %>% 
  ggplot(aes(step * time_step, effort, color = fleet2)) + 
  geom_line() + 
  scale_x_continuous(name = "year")
```

My plot output looks like below. Is that correct?
![image](https://user-images.githubusercontent.com/40546424/197266428-be2bc901-0549-491e-8118-5bc0660155be.png)

**Comment by DanOvando** [comment]
Huh are you talking about this figure here? Is the flat line what you're seeing when you run it locally?

https://danovando.github.io/marlin/articles/fleet-management_files/figure-html/unnamed-chunk-4-1.png
